### ISSUE TITLE
Please adapt your instructions for HELM deployment 

### ISSUE THREAD

**Issue by CarstenRilke** [anchore/enterprise-docs#111]
Hello,

in your OpenShift installation description, you specify the TILLER installation as a prerequisite.

https://docs.anchore.com/current/docs/installation/helm/openshift/

When using HELM 3 (e.g. v3.0.3) this is no longer necessary/possible as there is no suitable TILLER release available. (last tiller release: 2.16.1)

Please adapt your description accordingly.

Furthermore, there is no note that for an enterprise-demo a docker account has to be registered with you, to access the protected enterprise images. 

Many thanks and best regards,
Carsten

**Comment by zhill** [comment]
Thanks @CarstenRilke ! We'll get it updated

**Comment by Btodhunter** [comment]
@CarstenRilke all helm docs have been updated to remove references to tiller/helm2. Thanks!
