### ISSUE TITLE
Create documentation around feed sync timeouts

### ISSUE THREAD

**Issue by anchoresupport** [anchore/enterprise-docs#115]
Issue occurred where a feed sync was failing between the policy engine and enterprise feeds service; loading the first page of data was taking longer than the default feedReadTimeout (60 seconds).  

Suggest adding instructions to both the enterprise-docs and helm chart around upping the timeout to allow large data syncs to complete as subsequent syncs should take less time.<br><br><i>(created from <a href='https://anchore.zendesk.com/agent/tickets/2043'>Zendesk ticket #2043</a>)<br>gz#2043</i>

**Comment by zhill** [comment]
The software itself has updated to make this not an issue. Closing. If similar issues persist, please open a new issue.
