### ISSUE TITLE
Include Instruction Link in the Kubernetes Integration Page

### ISSUE THREAD

**Issue by grifonas** [anchore/enterprise-docs#132]
Would be really helpful to have a link to the instructions on how to integrate Anchore with Kubernetes on the `Kubernetes Integration` page.
Thank you!

**Comment by zhill** [comment]
Hi @grifonas , do you mean a link the [Admission Controller](https://github.com/anchore/kubernetes-admission-controller) on the [Kubernetes Integration](https://docs.anchore.com/current/docs/using/integration/kubernetes/) page specifically?

**Comment by grifonas** [comment]
Hi,
I mean the actual `Kubernetes Integration` page. As a new user I was i little lost as to where to find K8S instructions. No matter how I looked for it I kept coming back to that page. That's why I'm suggesting it.

**Comment by Btodhunter** [comment]
@grifonas we added a little note pointing people to the helm installation doc on the k8s integrations page. Thanks!
