### ISSUE TITLE
Upgrade versions for inline_scan docs

### ISSUE THREAD

**Issue by found-it** [anchore/enterprise-docs#145]
The inline scan version in these docs is still 0.6.0, can we update that to reflect the latest version?

* https://docs.anchore.com/current/docs/using/integration/ci_cd/inline_analysis/
* https://docs.anchore.com/current/docs/using/integration/ci_cd/inline_scanning/

**Comment by Btodhunter** [comment]
Thanks for pointing this out! Docs have been updated to use the `latest` inline-scan scripts.
