### ISSUE TITLE
Users in account getting 'Unauthorized' error

### ISSUE THREAD

**Issue by vikassinha2019** [anchore/enterprise-docs#159]
I am getting unauthorised error for anchore-cli users.

> Vikass-MBP-2:myrepo vikas$ anchore-cli account user list --account myaccount
Name                                     Type          Source        Created                     
myuser                               native        None          2020-03-08T15:55:02Z        
myjamuser                         native        None          2020-03-13T09:49:43Z        
dockerregistryprod           native        None          2020-04-27T10:26:04Z        
dockerRegistryStaging        native        None          2020-04-28T12:17:21Z        

> Vikass-MBP-2:myrepo vikas$ 
> Vikass-MBP-2:myrepo vikas$ anchore-cli --u dockerregistrystaging --p 'zSNgAs/TR' account whoami
> "Unauthorized"
> Vikass-MBP-2:myrepo vikas$ 
> Vikass-MBP-2:myrepo vikas$ 
> Vikass-MBP-2:myrepo vikas$ anchore-cli --u dockerregistrystaging --p 'SNgAs/TR'  --url https://anchore-dev.domain.com/v1  account whoami
> "Unauthorized"
> Vikass-MBP-2:myrepo vikas$ 
> Vikass-MBP-2:myrepo vikas$

**Comment by zhill** [comment]
This is not the correct repository for filing this issue. It should be opened in anchore/anchore-engine. Please open it there and we can help. I'm closing it here as it isn't a documentation issue.
