### ISSUE TITLE
swagger ui config file missing from server

### ISSUE THREAD

**Issue by bretteville** [anchore/enterprise-docs#191]
Following your quick start to set up swagger I attempted to 

curl https://docs.anchore.com/current/docs/quickstart/anchore-swaggerui.conf > anchore-swaggerui-nginx.con

This results in a 404
`cat anchore-swaggerui-nginx.conf
<html>404 Not found</html>`

Please change the documentation or ad the sample config file to the server.

**Comment by zhill** [comment]
Where is the reference for this? I only see  https://docs.anchore.com/current/docs/quickstart/anchore-swaggerui-nginx.conf in the quickstart guide, which does exist. Is there another reference?

**Comment by bretteville** [comment]
Thanks for your quick reply Zach.

Down at the bottom of this page the url is invalid
https://docs.anchore.com/current/docs/engine/quickstart/

It says https://docs.anchore.com/current/docs/quickstart/anchore-swaggerui.conf where it should say https://docs.anchore.com/current/docs/quickstart/anchore-swaggerui-nginx.conf

Which is why I got the 404, the url above is correct.

**Comment by zhill** [comment]
Thanks. I'll fix it. That should refer to the engine/ paths for the configs anyway.

**Comment by bretteville** [comment]
Got it working now, after fixing one minor discrepancy in the nginx config. For the upstream api server the hostname in the config is "engine-api". Using the docker-compose file it comes up as simply "api".
