### ISSUE TITLE
helm install anchore-demo stable/anchore-engine not working with  k8 version 1.16

### ISSUE THREAD

**Issue by cramakan** [anchore/enterprise-docs#203]
helm install anchore-demo stable/anchore-engine not working with  k8 version 1.16

Gettting error as 
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"

**Comment by Btodhunter** [comment]
Hey @cramakan - thanks for pointing this out! The docs are actually out of date, our new helm chart over at https://github.com/anchore/anchore-charts/tree/master/stable/anchore-engine works with k8s v1.15+. I put in a PR to fix the documentation.

**Comment by cramakan** [comment]
Thank you  its working  with  k8 1.16
