### ISSUE TITLE
Quickstart

### ISSUE THREAD

**Issue by mikesuding** [anchore/enterprise-docs#235]
Please change this sentence to be more realistic 2+ hours.

Note: The first time you run Anchore Enterprise, it will take some time (10+ minutes, depending on network speed) 

In testing that Paul N., Brent and I did, this initial sync takes 2-3 hours. It doesn't seem to depend very much on network speed. I compared it between 50Mbps and 100Mbps and it only changed by a few minutes.

**Comment by zhill** [comment]
Yes, it's grown as we add more feed data for more kinds of vulnerability matches
