### ISSUE TITLE
Policy bundles are stored per account rather than user

### ISSUE THREAD

**Issue by rchench** [anchore/enterprise-docs#241]
According to the doc, policy bundles are stored for each user. This gives an impression that each user can have different policy bundles and set active bundle seperately.
> The Anchore Engine can store multiple policy bundles for each user, but only one bundle can be active at any point in time

However, after testing, the policy bundles are actually stored for each account. Different users in the same account share the same policy bundles and active one. So I suggest to update this doc for clarity.

**Comment by zhill** [comment]
@rchench thanks for filing this. Apologies in the delay for response. Will get it updated!

**Comment by rchench** [comment]
Thank you.
