### ISSUE TITLE
Separate Engine from Enterprise docs

### ISSUE THREAD

**Issue by nwl** [anchore/enterprise-docs#244]
- [ ] Remove mention of Anchore Engine quickstart from https://docs.anchore.com/current/docs/quickstart/

- [ ] Remove "What is Anchore Engine" and "Anchore Enterprise vs Anchore Engine" comparison from https://docs.anchore.com/current/docs/overview/concepts/ [This question can be left in the FAQ]

- [ ] Remove Open Source section from the FAQ at https://docs.anchore.com/current/docs/faq/ and replace Anchore Engine with Anchore Enterprise throughout. 

- [ ] Replace Anchore Engine with Anchore Enterprise at https://docs.anchore.com/current/docs/overview/concepts/images/

- [ ] Replace Anchore Engine with Anchore Enterprise at https://docs.anchore.com/current/docs/overview/concepts/policy/bundles/

- [ ] Replace Anchore Engine with Anchore Enterprise at https://docs.anchore.com/current/docs/overview/requirements/

- [ ] https://docs.anchore.com/current/docs/engine/engine_installation/configuration/ needs to be copied to the Enterprise tree.

- [ ] https://docs.anchore.com/current/docs/engine/engine_installation/upgrade/ needs to be copied to the Enterprise tree.

- [ ] Replace Anchore Engine with Anchore Enterprise at https://docs.anchore.com/current/docs/data_privacy/

- [ ] Replace Anchore Engine with Anchore Enterprise at https://docs.anchore.com/current/docs/troubleshooting/

- [ ] Remove https://docs.anchore.com/current/docs/engine/ from tree and replace with a 301 to Github URL.

**Comment by hev** [comment]
I think this all makes sense. A couple things.

We should keep the `What are the differences between Anchore Engine and Anchore Enterprise` and perhaps expand this section to consider toolbox (not necessarily within the scope of this issue).

While were doing this level of find/replace I also think we should use a site-wide variable for the product name `Anchore Enterprise`. This would be helpful if we have a version for Anchore Federal, or just want to expand the name to a more acronym friendly product description.

**Comment by nwl** [comment]
More...

On Enterprise landing page:

- [ ] Remove Engine button.
- [ ] Replace CircleCI element with Gitlab logo and new copy (I will provide). 
- [ ] Remove entire Related Content row
- [ ] Add Syft, Grpye links to Github links at bottom

New Engine docs should live at engine.anchore.io

**Comment by zburstein** [comment]
I compiled a list of image diagrams that reference engine that might also need to be updated:

- content/docs/overview/concepts/policy/AnchorePolicyEval.png
- content/docs/overview/concepts/images/AnalyzingImages.png
- content/docs/using/integration/ci_cd/ci-cd.png
- content/docs/overview/EnterpriseOverview.png
- content/docs/using/cli_usage/feeds/FeedsOverview.png
- content/docs/using/integration/kubernetes/k8s.png
- content/docs/using/cli_usage/registries/RegistryAccess.png

**Comment by zhill** [comment]
ack, thanks @zburstein for now let's keep that list here so we know what to update and we can do those after the main update.
