### ISSUE TITLE
Unable to add the Azure container registry

### ISSUE THREAD

**Issue by basavarajb** [anchore/enterprise-docs#246]
I'm Unable to add the registry  from the cli  using below command format

anchore-cli registry add  anchoreacr.azurecr.io abc xxxxx --skip-validate
 
abc : acr username
xxxxx : acr password

And also i tried with service principal also but im getting "Unauthorized" 
![image](https://user-images.githubusercontent.com/9286143/99566161-8bd8d580-29f2-11eb-904e-b31d5443b09a.png)

**Comment by zhill** [comment]
The unauthorized response is the CLI being unable to make the API call to load the credential, not the validity of the azure credential itself. If you haven't yet, make sure the environment vars ANCHORE_CLI_USER and ANCHORE_CLI_PASS are set to the credentials for Anchore itself (e.g. 'admin' and the admin password). That will allow the call to go thru and you can see if the azure creds themselves actually work.

**Comment by basavarajb** [comment]
How to create credential file in windows?

**Comment by basavarajb** [comment]
> The unauthorized response is the CLI being unable to make the API call to load the credential, not the validity of the azure credential itself. If you haven't yet, make sure the environment vars ANCHORE_CLI_USER and ANCHORE_CLI_PASS are set to the credentials for Anchore itself (e.g. 'admin' and the admin password). That will allow the call to go thru and you can see if the azure creds themselves actually work.
