### ISSUE TITLE
Github Driver Permissions Wrong

### ISSUE THREAD

**Issue by Vijay-P** [anchore/enterprise-docs#271]
[Link to page](https://docs.anchore.com/current/docs/installation/feeds/)

Here, it states that no permissions are required for the GitHub personal access token.
Please update docs link with following URL and correct text regarding permissions:
https://github.com/settings/tokens/new?scopes=user,public_repo,repo,repo_deployment,repo:status,read:repo_hook,read:org,read:public_key,read:gpg_key

**Comment by zhill** [comment]
@Vijay-P I don't think the token requires any permissions. Can you confirm that those are actually required for fetching the advisories db? That isn't tied to any specific repo, so only authentication as a user should be necessary

**Comment by zhill** [comment]
bump
