### ISSUE TITLE
Image not displaying

### ISSUE THREAD

**Issue by ethicalmohit** [anchore/enterprise-docs#40]
I am not able to see any image attached to the documentation at docs.anchore.com. Images URLs are giving out 404 error on opening. 

Ref: https://docs.anchore.com/current/docs/engine/general/concepts/images/

Any alternative URL to study?

**Comment by katgurdak** [comment]
Hi @ethicalmohit,

Thanks for notifying us on this issue! We've recently migrated our documentation so the image references weren't lining up right. This should be fixed in #43 but feel free to let us know if there's anything else.
