### ISSUE TITLE
Policy Bundles - Wrong Mappings and Whitelists definitions

### ISSUE THREAD

**Issue by Pablo-CC** [anchore/enterprise-docs#54]
https://docs.anchore.com/current/docs/overview/concepts/policy/bundles/

Here we can read these definitions for _Mappings_ and _Whitelists_ which, as I see it, don't correspond but are interexchanged.

- **Mappings** - Named sets of rule exclusions to override a match in a policy rule
- **Whitelists** - Ordered rules that determine which policies and whitelists should be applied to a specific image at evaluation time.

The correct definitions should be:
- **Mappings**  - Ordered rules that determine which policies and whitelists should be applied to a specific image at evaluation time.
- **Whitelists*** - Named sets of rule exclusions to override a match in a policy rule

**Comment by zhill** [comment]
Thanks. Yes you are correct. We'll fix that.
