### ISSUE TITLE
image analysis

### ISSUE THREAD

**Issue by ealessi** [anchore/enterprise-docs#72]
What are the 'inline links' you're referring to in the documentation page for registering repositories and 'navigating through the inline links' ?
 
Maybe describing this a bit more thoroughly would not leave is in the dark for this pre-populating fields feature.

**Comment by blang9238** [comment]
Hi @ealessi, I'll put in some clarification around that.  The inline links are simply the clickable values that appear under registry name (e.g., docker.io), repository name (e.g., alpine), or tag version (e.g., latest).

**Comment by blang9238** [comment]
Resolved by PR #82
